
-- accounts;

CREATE TABLE public.accounts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	balance float8 NULL,
	account_number numeric NULL,
	bank_id numeric NULL,
	identification_number numeric NULL,
	CONSTRAINT accounts_pk PRIMARY KEY (id)
);
CREATE INDEX accounts_account_number_idx ON public.accounts USING btree (account_number);
CREATE INDEX accounts_bank_id_idx ON public.accounts USING btree (bank_id);
CREATE INDEX accounts_identification_number_idx ON public.accounts USING btree (identification_number);
CREATE UNIQUE INDEX accounts_uniq_idx ON public.accounts USING btree (identification_number, bank_id);

-- account_owners;

CREATE TABLE public.account_owners (
	id bigserial NOT NULL,
	contact_number int8 NULL,
	first_name varchar(255) NULL,
	identification_number int8 NULL,
	last_name varchar(255) NULL,
	mail_address varchar(255) NULL,
	CONSTRAINT account_owners_pkey PRIMARY KEY (id)
);

-- banks;

CREATE TABLE public.banks (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NULL,
	country_code varchar(255) NULL,
	CONSTRAINT banks_pk PRIMARY KEY (id)
);

-- transactions;

CREATE TABLE public.transactions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric NULL,
	account_number int8 NULL,
	transaction_date int8 NULL,
	transaction_type int4 NOT NULL,
	success bool NULL,
	CONSTRAINT transactions_pk PRIMARY KEY (id)
);
CREATE INDEX transactions_account_number_idx ON public.transactions USING btree (account_number, transaction_date);
CREATE INDEX transactions_account_type_idx ON public.transactions USING btree (account_number, transaction_type);
CREATE INDEX transactions_transaction_date_idx ON public.transactions USING btree (transaction_date);