# Use postgres/example user/password credentials
version: '3.1'

networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    networks:
      - mynetwork
